image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      if [ "$GITPOD_HEADLESS" = "true" ]; then
        # force non-interactive terminal in prebuilds
        export TERM=dumb
      fi

      # run standard gradle build
      ./gradlew localDistro

#jetbrains:
#  intellij:
#    prebuilds:
#      version: stable

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - eamodio.gitlens
